Budget_APP V.01
gjuliao/budget_app pull request #10
Opened 2023-04-27 20:20 UTC by gjuliao

# Details
Capstone Project RoR.

### Design

- Following these [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), including:
- Colors.
- Typography: font face, size and weight.
- Layout: composition and space between elements.

### Splash screen

A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.
Sign up and log in pages

- The user should be able to register in the app with full name, email and password (all mandatory).
- The user can log into the app using email and password.
- If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

### Home page (categories page)

- When the user logs in, they are presented with the categories page.
- For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
- When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
- There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

### Transactions page

- For a given category, the list of transactions is presented, ordered by the most recent.
- At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
- There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

### "Add a new category" page

The user fills out a form to create a new category, indicating their name and icon (both mandatory).
The user clicks (or taps) the "Save" button to create the new category and is taken to the home page on success.
When the user clicks on the "Back" button (<), the user navigates to the home page.

### "Add a new transaction" page

- The user fills out a form to create a new transaction with:
- name (mandatory)
- amount (mandatory)
- categories (mandatory at least one)
- The user click (or taps) the "Save" button to create the new transaction and is taken to the transactions page for that category.
- When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

### Testing requirements

- Create unit and integration tests for all the most important components of your RoR application.
- Technical requirements
- You should use Postgres as your database.
- You should use devise for authentication.
- You should validate all user input to make sure that anyone with bad intentions cannot compromise your app.
- You can use a view template engine of your choice (.erb, .slim, .haml).
- The project should be deployed and accessible online.
- Your database schema should reflect the following structure:

2023-04-27 21:41 UTC, BenMukebo requested changes
## Hi @gjuliao, 

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


### To Highlight 🎉
- PR has a good title and summary. ✔️
- The user input has validations. ✔️
- Well set up devise for authentication. 🥇 


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

### Video presentation

- [ ] It's one of the project requiements you receord a video presenting the features of the project and make sure that The maximum length of the video is 5 minutes. Kindly address this 👍🏻 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 21:41 UTC, BenMukebo commented on README.md
> +
- [x] The README file should contain an "Acknowledgements"  that give appropriate credit. kindly, let's  gives appropriate credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) as the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/). ✍🏻

2023-04-27 21:41 UTC, BenMukebo commented on README.md
> +
##### **Live version**

- [ ] It's one of the project requirements you deploy the application using Render, Netlify, or GitHub Pages and make sure that:
  - The project is deployed properly, and the home, Category, and Transaction page works as expected.
  -  A link to the deployed project should be present in the README.

2023-04-27 21:41 UTC, BenMukebo commented on app/models/entity.rb
> +  has_many :groups
- [x] The database schema should reflect the following structure:

![image](https://user-images.githubusercontent.com/79058364/227439921-57baa020-2dfb-42d7-9613-d4a21a80577a.png)

- [x] According to the Entity relational database Diagram, there is a many-to-many relationship between Group and Entity so, You should have created a join table to link the Entity table with the Group table. Kindly address this 💯 😉 
- Note: In Rails and PostgreSQL, creating a join table is necessary for modeling many-to-many relationships because it allows us to establish a connection between two tables without duplicating data.

2023-04-27 21:41 UTC, BenMukebo commented on app/views/groups/index.html.erb
> +</div>
- [ ] Kindly follow the provided design (width, font, size, height, background, color...)  and make sure you add this white border around the Add Category button text. 👍🏻 The `New Transaction` button has a similar problem. Kindly fix it as well. 💯  👍🏻

- Original
![image](https://user-images.githubusercontent.com/79058364/230731290-6f44f560-b369-4d7e-9e4b-51130a17508b.png)

- Your Button
![image](https://user-images.githubusercontent.com/79058364/230731159-54b4dfeb-7147-4435-b66b-cad0835ba595.png)

2023-04-27 21:41 UTC, BenMukebo commented on app/views/groups/new.html.erb
> +</div>
- [ ] Great job so far 👍🏻 However the `Back to group` button should be a back icon placed in the header navbar. Kindly address this 

Your Implementation | Original Design
:---:|:---:
![image](https://user-images.githubusercontent.com/79058364/234993167-9f2db0a8-c92c-45e0-9a18-8fd879c5e045.png) | ![image](https://user-images.githubusercontent.com/79058364/234993723-2af7342c-31de-472a-9c98-6faf479fa494.png)

2023-04-27 21:41 UTC, BenMukebo commented on app/views/groups/_group.html.erb
> +</div>
- Kindly improve the design, Check these [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), including:
* Colors
* Typography: font face, size, and weight.
* Layout: composition and space between elements.
- [ ] Kindly follow the provided design (width, font, size, height, background, color...)
 -  Add this white border around the ADD CATEGORY button text. 👍🏻 
 - The NEW TRANSACTION button has a similar problem. Kindly fix it as well. 💯  👍🏻
 - The total amount number should be bold and the text should be normal, Please increase this font width. 👍🏻
 - The card should have a category image, name, `created date`, and amount. kindly let's display the creation date for each category card. 🛀🏻 

Your Implementation | Original Design
:---:|:---:
![image](https://user-images.githubusercontent.com/79058364/234994302-d9b0bff7-fb2f-4229-8f1d-25922cd04eef.png) | ![image](https://user-images.githubusercontent.com/79058364/219786288-a43c8eb4-d309-4b09-9b4e-02b929ccd7fb.png)

2023-04-27 21:41 UTC, BenMukebo commented on app/views/entities/_entity.html.erb
> +  </div>
### "Transactions page"

- [ ] For a given category, the list of transactions should be presented ordered by the most recent. kindly address this. 👇🏻 
![image](https://user-images.githubusercontent.com/79058364/234995321-7bf77dd7-7633-41d6-ba81-9c891e6db518.png)

2023-04-27 21:41 UTC, BenMukebo commented on app/views/entities/_form.html.erb
> +    </div>
### Add a new transaction page

- [ ]  According to the project requirements, When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category and not the Home Page. Kindly correct this as well. ✍🏻 
- [ ] It's one of the project requirements that The user fills out a form to create a new transaction or expense with these mandatory parameters:
* name (mandatory)
* amount (mandatory)
* categories (mandatory at least one).  kindly prevent the user to create a new transaction without selecting at least one  categories 

![image](https://user-images.githubusercontent.com/79058364/234995505-67351f36-166e-4d86-9bad-a39fc7d93050.png)

2023-04-27 21:41 UTC, BenMukebo commented on test/models/group_test.rb
> +end
- [ ] Great job so far 👏🏻 However according to the project requirements. The App should have unit tests and integration tests for all the most important components of the RoR application. Kindly make sure all the components have `unit tests` tests ✍🏻

2023-04-28 13:42 UTC, MahmoudBakr23 approved these changes
Hi @gjuliao😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done on implementing the changes requested by the previous reviewer
- Nice work enhancing the design tips
- Good job recording the presentation video and deploying the app

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 13:46 UTC, merged